// examples/react/advanced/App.tsx
import { ChartRendererRegistry } from '@datafe-open/markdown-chart';
import { createEChartsRenderer } from '@datafe-open/markdown-chart-echarts';
import {
  createMarkdownChartComponents,
  MarkdownChartProvider,
} from '@datafe-open/markdown-chart-react';
import { useMemo } from 'react';
import ReactMarkdown from 'react-markdown';

const source = `# Sales

\`\`\`markdown-chart
{
  "version": 1,
  "renderer": "echarts",
  "data": {
    "kind": "inline",
    "dimensions": ["category", "value"],
    "source": [["A", 10], ["B", 20]]
  },
  "spec": {
    "xAxis": { "type": "category" },
    "yAxis": {},
    "series": [{ "type": "bar", "encode": { "x": "category", "y": "value" } }]
  }
}
\`\`\``;

const chartComponents = createMarkdownChartComponents({
  chartStyle: { minHeight: 360 },
});

export function App() {
  const registry = useMemo(
    () => new ChartRendererRegistry().register(createEChartsRenderer()),
    [],
  );

  return (
    <MarkdownChartProvider registry={registry}>
      <ReactMarkdown components={chartComponents}>{source}</ReactMarkdown>
    </MarkdownChartProvider>
  );
}

// examples/vue/advanced/App.vue
<script setup lang="ts">
import { ChartRendererRegistry } from '@datafe-open/markdown-chart';
import { createEChartsRenderer } from '@datafe-open/markdown-chart-echarts';
import { markdownChartPlugin } from '@datafe-open/markdown-chart-markdown-it';
import { MarkdownChart } from '@datafe-open/markdown-chart-vue';
import MarkdownIt from 'markdown-it';

const source = `# Sales

\`\`\`markdown-chart
{
  "version": 1,
  "renderer": "echarts",
  "data": {
    "kind": "inline",
    "dimensions": ["category", "value"],
    "source": [["A", 10], ["B", 20]]
  },
  "spec": {
    "xAxis": { "type": "category" },
    "yAxis": {},
    "series": [{ "type": "bar", "encode": { "x": "category", "y": "value" } }]
  }
}
\`\`\``;

const registry = new ChartRendererRegistry().register(createEChartsRenderer());
const markdownIt = new MarkdownIt({ html: false }).use(markdownChartPlugin, {
  registry,
});
</script>

<template>
  <MarkdownChart
    :source="source"
    :markdown-it="markdownIt"
    :registry="registry"
  />
</template>
