// examples/vue/AdvancedExample.vue
<script setup lang="ts">
import { ChartRendererRegistry } from '@datafe/markdown-chart';
import { createEChartsRenderer } from '@datafe/markdown-chart-echarts';
import { markdownChartPlugin } from '@datafe/markdown-chart-markdown-it';
import { MarkdownChart } from '@datafe/markdown-chart-vue';
import MarkdownIt from 'markdown-it';

defineProps<{ source: string }>();

const registry = new ChartRendererRegistry().register(createEChartsRenderer());
const markdownIt = new MarkdownIt({ html: false }).use(markdownChartPlugin, {
  registry,
});
</script>

<template>
  <MarkdownChart
    :source="source"
    :markdown-it="markdownIt"
    :registry="registry"
  />
</template>

// examples/react/AdvancedExample.tsx
import { ChartRendererRegistry } from '@datafe/markdown-chart';
import { createEChartsRenderer } from '@datafe/markdown-chart-echarts';
import {
  createMarkdownChartComponents,
  MarkdownChartProvider,
} from '@datafe/markdown-chart-react';
import { useMemo } from 'react';
import ReactMarkdown from 'react-markdown';

const chartComponents = createMarkdownChartComponents({
  chartStyle: { minHeight: 360 },
});

export interface AdvancedExampleProps {
  readonly source: string;
}

export function AdvancedExample({ source }: AdvancedExampleProps) {
  const registry = useMemo(
    () => new ChartRendererRegistry().register(createEChartsRenderer()),
    [],
  );

  return (
    <MarkdownChartProvider registry={registry}>
      <ReactMarkdown components={chartComponents}>{source}</ReactMarkdown>
    </MarkdownChartProvider>
  );
}
